language: ruby
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install: 
  - bundle update
  - bundle install

script: 
  - bundle exec jekyll build
after_success:
  - bash <(curl -s https://codecov.io/bash)
  

