language: ruby
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install: 
  - gem install jekyll
  - gem install rouge
  - gem install jekyll-paginate
  - gem install jemoji
script: 
  - jekyll build
after_success:
  - bash <(curl -s https://codecov.io/bash)
  

